# Generated by Django 4.2 on 2023-05-14 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_account_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='unhashed_pw',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
