# Generated by Django 4.2 on 2023-04-14 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='passenger_count_domestic',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='passenger_count_international',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='passenger_count_local',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='total_bill',
            field=models.FloatField(null=True),
        ),
    ]
