# Generated by Django 4.2 on 2023-04-24 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_vehicle_passenger_count_domestic_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domestic_rate', models.PositiveIntegerField()),
                ('local_rate', models.PositiveIntegerField()),
                ('international_rate', models.PositiveIntegerField()),
            ],
        ),
    ]
