# Generated by Django 4.2 on 2023-05-30 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_vehicle_vehicle_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='domestic_bill',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='international_bill',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='local_bill',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
