# Generated by Django 4.2 on 2023-06-02 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_vehicle_domestic_bill_vehicle_international_bill_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='status',
            field=models.CharField(default='Not Used', max_length=10, null=True),
        ),
    ]
